# Generated by Django 3.0.5 on 2020-04-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='fullname',
        ),
    ]
