# Generated by Django 3.0.5 on 2020-04-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
