# Generated by Django 3.0.5 on 2020-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_remove_shippingaddress_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
