# Generated by Django 3.0.5 on 2020-04-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20200419_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='street2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
