# Generated by Django 3.0.5 on 2020-04-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20200419_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='item',
        ),
        migrations.AddField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(to='profile.Product'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='items',
            field=models.ManyToManyField(to='profile.Product'),
        ),
    ]
