# Generated by Django 3.0.5 on 2020-04-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20200419_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Basket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Product')),
            ],
        ),
    ]
