# Generated by Django 3.0.5 on 2020-04-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_itembasket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='items',
        ),
        migrations.AddField(
            model_name='basket',
            name='totalAmount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
