# Generated by Django 3.0.5 on 2020-04-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_remove_shippingaddress_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
