# Generated by Django 3.0.5 on 2020-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20200422_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
