# Generated by Django 3.0.5 on 2020-04-20 21:46

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20200420_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[profile.models.validate_price]),
        ),
    ]
