# Generated by Django 3.0.5 on 2020-04-21 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20200420_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='items',
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.OrderHistory')),
            ],
        ),
    ]
