# Generated by Django 3.0.5 on 2020-04-21 01:44

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20200421_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, validators=[profile.models.validate_price]),
        ),
        migrations.AlterField(
            model_name='itembasket',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40),
        ),
    ]
