# Generated by Django 3.0.5 on 2020-04-16 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
